### ISSUE TITLE
v3.3.7 中有两个符号和 AFNetworking 3.0 是重复的，导致编译失败

### ISSUE THREAD

**Issue by zhang-hu** [niuxinghua/UserCenter#1]
v3.3.7 中有两个符号和 AFNetworking 3.0 是重复的，导致编译失败
<img width="879" alt="2018-01-16 10 55 05" src="https://user-images.githubusercontent.com/19181721/34969955-7ca5cdf2-faac-11e7-8e43-fa96a571e924.png">

**Comment by niuxinghua** [comment]
3.3.9解决了这个问题
